# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('guest_comment', models.CharField(max_length=300, null=True)),
                ('comming', models.BooleanField()),
                ('pair', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('our_comment', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
