# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedLanding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_comment',
            field=models.TextField(null=True),
        ),
    ]
