# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedLanding', '0002_auto_20160523_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='our_comment',
            field=models.TextField(null=True),
        ),
    ]
